# Generated by Django 2.2.1 on 2019-05-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Fundation'), (2, 'Partners'), (3, 'Locals')])),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
