# Generated by Django 2.2.1 on 2019-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.IntegerField(choices=[(1, 'Foundation'), (2, 'Partners'), (3, 'Locals')]),
        ),
    ]
