# Generated by Django 2.2.1 on 2019-05-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190527_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='qwerty', max_length=32),
        ),
    ]
